<?php
/**
 * ChatApp · 维护门户 i18n（English / 简体中文）
 *
 * 维护门户（portal.php）与维护登录页（index.php）共用这一份语言包：
 *   - 语言选择存在 cookie `maint_lang`（en / zh），默认 zh（简体中文）
 *   - PHP 侧用 mt('key') 输出；JS 侧用 maint_lang_js() 注入 JSON 后用 MT.key 取
 *   - 左下角的下拉框由 maint_lang_select() 输出（两个页面各自摆位）
 *
 * 注意：门户要在 DB 挂掉时也能用，所以本文件不依赖 api/config.php。
 */

if (!function_exists('maint_lang')) {
    function maint_lang(): string {
        $v = (string)($_COOKIE['maint_lang'] ?? 'zh');
        return in_array($v, ['en', 'zh'], true) ? $v : 'zh';
    }
}

$GLOBALS['MAINT_LANG'] = maint_lang();

if (!function_exists('mt')) {
    /** 取当前语言的文案（找不到就退到英文，再找不到就回显 key） */
    function mt(string $k): string {
        global $MAINT_MT;
        $lang = $GLOBALS['MAINT_LANG'] ?? 'zh';
        return (string)($MAINT_MT[$lang][$k] ?? $MAINT_MT['en'][$k] ?? $k);
    }
}

if (!function_exists('maint_lang_js')) {
    /** 把当前语言包注入给前端 JS（portal.php 里 var MT = <?php echo maint_lang_js(); ?>） */
    function maint_lang_js(): string {
        global $MAINT_MT;
        $lang = $GLOBALS['MAINT_LANG'] ?? 'zh';
        return json_encode($MAINT_MT[$lang] ?? $MAINT_MT['en'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }
}

if (!function_exists('maint_lang_select')) {
    /** 语言下拉框（左下角）；切换后写 cookie 并刷新 */
    function maint_lang_select(string $attrs = ''): string {
        $lang = $GLOBALS['MAINT_LANG'] ?? 'zh';
        $sel = function (string $v) use ($lang) { return $v === $lang ? ' selected' : ''; };
        return '<select id="maintLangSel" onchange="maintSetLang(this.value)" ' . $attrs . '>'
            . '<option value="en"' . $sel('en') . '>English</option>'
            . '<option value="zh"' . $sel('zh') . '>简体中文</option>'
            . '</select>';
    }
}

if (!function_exists('maint_lang_switcher_js')) {
    /** 语言切换的公共 JS（拿到 cookie 作用域内全站可用） */
    function maint_lang_switcher_js(): string {
        return 'function maintSetLang(v){ document.cookie = "maint_lang=" + (v === "en" ? "en" : "zh") + ";path=/;max-age=31536000"; location.reload(); }';
    }
}

$MAINT_MT = [
    'en' => [
        /* 通用 */
        'portal_name' => 'Maintenance Portal',
        'lang_label' => 'Language',
        'badge_maint' => 'Maintenance',
        'badge_online' => 'Online',
        'yes' => 'Yes',
        'no' => 'No',
        'logout' => 'Logout',
        'logout_home' => 'Logout & Return to ChatApp',
        'failed' => 'Failed',
        'net_err' => 'Network error / no response',
        'all_fields_required' => 'All fields are required',
        'git_hash_mismatch' => 'Git hash mismatch',
        /* 侧栏 */
        'nav_dash' => 'Dashboard',
        'nav_settings' => 'Settings',
        'nav_creds' => 'Credentials',
        'nav_accounts' => 'Accounts',
        'nav_upgrade' => 'Upgrade',
        'nav_downgrade' => 'Downgrade',
        'nav_factory' => 'Factory Reset',
        'nav_uninstall' => 'Uninstall',
        'nav_links' => 'Quick Links',
        /* 仪表盘 */
        'card_maint_mode' => 'Maintenance Mode',
        'btn_enable_maint' => 'Enable Maintenance',
        'btn_disable_maint' => 'Disable Maintenance',
        'note_visitors' => 'All visitors see the maintenance page. Portal and admin credentials can still log in.',
        'maint_on' => 'Maintenance mode enabled',
        'maint_off' => 'Maintenance mode disabled',
        'card_current_settings' => 'Current Settings',
        'k_return_code' => 'Return Code',
        'k_maint_page' => 'Maintenance Page',
        'k_allow_login' => 'Allow Maintenance Login',
        'k_use_mysql' => 'Use MySQL Credentials',
        'card_server_info' => 'Server Info',
        'k_git' => 'Git HEAD',
        'k_disk' => 'Free Disk',
        'k_time' => 'Server Time',
        'reachable' => 'Reachable',
        'down' => 'Down',
        'card_quick_actions' => 'Quick Actions',
        'link_maint_login' => 'Maintenance Login',
        /* 设置面板 */
        'set_card' => 'Maintenance Mode Settings',
        'lbl_maint_mode' => 'Maintenance Mode',
        'opt_running' => 'Running (disable maintenance)',
        'opt_maintenance' => 'Maintenance (enable maintenance)',
        'chk_allow_login' => 'Allow maintenance login (shows the Admin Login link on the maintenance page)',
        'chk_mysql_creds' => 'Use MySQL credentials for maintenance login (validate account in DB)',
        'btn_save' => 'Save',
        'btn_preview' => 'Preview Page',
        'note_changes' => 'Changes take effect immediately. Preview opens the selected page in a new tab.',
        'settings_saved' => 'Settings saved',
        'save_failed' => 'Save failed',
        /* 门户凭据 */
        'creds_card' => 'Change Maintenance Portal Username / Password',
        'creds_note' => 'You must verify the current administrator password (uid 10000). Saving invalidates old maintenance tokens and you will need to log in again.',
        'lbl_cur_pwd' => 'Current Admin Password (required)',
        'lbl_m_user' => 'Maintenance Username (3-20)',
        'lbl_m_pass' => 'Maintenance Password (≥8)',
        'btn_save_relogin' => 'Save & Re-login',
        'need_cur_pwd' => 'Please enter the current admin password',
        'bad_m_user' => 'Maintenance username must be 3-20 letters/numbers/underscore',
        'bad_m_pass' => 'Maintenance password must be at least 8 chars',
        'creds_updated' => 'Credentials updated, re-logging in...',
        /* 账号锁定 */
        'acc_card' => 'Account Lock Manager',
        'acc_note' => 'Look up any account by username or UID, view its current lock status (failed attempts / locked until), then unlock or manually lock it.',
        'lbl_query' => 'Username or UID',
        'ph_query' => 'e.g. admin or 10001',
        'btn_lookup' => 'Look up',
        'need_query' => 'Enter a username or UID',
        'not_found' => 'Not found',
        'role_owner' => 'Owner',
        'role_admin' => 'Administrator',
        'role_user' => 'User',
        'ac_account' => 'Account',
        'ac_display' => 'Display name',
        'ac_role' => 'Role',
        'ac_enabled' => 'Enabled / Placeholder',
        'ac_restricted' => 'Restricted',
        'ac_failed' => 'Failed attempts',
        'ac_lock_status' => 'Lock status',
        'ac_last_login' => 'Last login',
        'ac_locked' => 'LOCKED',
        'ac_until' => '— until',
        'ac_min_left' => 'min left',
        'ac_not_locked' => 'Not locked',
        'ac_lock_for' => 'Lock for',
        'ac_min15' => '15 minutes',
        'ac_min30' => '30 minutes',
        'ac_hour1' => '1 hour',
        'ac_hour3' => '3 hours',
        'ac_hour24' => '24 hours',
        'ac_day7' => '7 days',
        'ac_lock_btn' => 'Lock account',
        'ac_unlock_btn' => 'Unlock account',
        'ac_confirm_unlock' => 'Unlock this account and reset failed attempts?',
        'ac_locked_until' => 'Locked until ',
        'ac_lock_failed' => 'Lock failed',
        'ac_unlocked' => 'Account unlocked',
        'ac_unlock_failed' => 'Unlock failed',
        /* 快捷链接 */
        'links_card' => 'Shortcuts',
        'link_relogin' => 'Maintenance Login (re-login)',
        'links_note' => 'Danger operations (Upgrade / Downgrade / Factory Reset / Uninstall) are handled directly in this portal via the sidebar.',
        /* 升级 */
        'up_card' => 'Upgrade ChatApp',
        'up_note' => 'Pulls from github.com/lqx211/ChatApp and overwrites code. config/ and data/ are kept, and maintenance credentials are preserved. Uncommitted changes will be overwritten.',
        'k_branch' => 'Branch',
        'k_current' => 'Current',
        'k_remote' => 'Remote',
        'k_uncommitted' => 'Uncommitted',
        'btn_check_updates' => 'Check for updates',
        'btn_checking' => 'Checking...',
        'lbl_admin_pwd' => 'Administrator Password (10000)',
        'lbl_m_secret' => 'Maintenance Passphrase',
        'lbl_git1' => 'Current git hash',
        'lbl_git2' => 'Re-enter git hash',
        'chk_risk' => 'I understand and accept the risk',
        'btn_upgrade_now' => 'Upgrade now',
        'up_starting' => 'Starting…',
        'up_step_done' => 'Upgrade complete',
        'up_step_failed' => 'Upgrade failed',
        'up_check_failed' => 'Check failed',
        'up_available' => 'Update available → ',
        'up_to_date' => 'Already up to date',
        'up_accept_risk' => 'Please accept the risk',
        'up_started' => 'Upgrade started — maintenance armed',
        'up_released' => 'Upgrade failed — maintenance released',
        'up_complete' => 'Upgrade complete — service restored',
        /* 降级 */
        'dg_card' => 'Downgrade System',
        'dg_note' => 'EXTREMELY DANGEROUS: reverts the entire codebase to an older version. Database schema and code may become incompatible. Effectively one-way.',
        'lbl_current_ver' => 'Current version',
        'lbl_target_ver' => 'Select target version',
        'chk_dg_risk' => 'I understand this is extremely dangerous',
        'btn_downgrade_now' => 'Downgrade now',
        'dg_loading' => 'Loading versions…',
        'dg_load_failed' => 'Failed to load versions',
        'dg_confirm' => 'Please confirm before downgrading',
        'dg_done' => 'Downgrade done: ',
        'dg_complete' => 'Downgrade complete',
        'dg_failed' => 'Downgrade failed',
        /* 重置出厂 */
        'fr_card' => 'Factory Reset ChatApp',
        'fr_note' => 'Drops and rebuilds the database, creates a new administrator, and wipes all users/data. A mysqldump backup is taken automatically unless skipped.',
        'lbl_new_admin' => 'New Admin Username (3-20)',
        'lbl_new_admin_pw' => 'New Admin Password (min 8)',
        'lbl_new_m_user' => 'New Maintenance Username (optional)',
        'lbl_new_m_pass' => 'New Maintenance Password (optional)',
        'chk_skip_dump' => 'Skip automatic database backup',
        'chk_fr_risk' => 'I understand all data will be wiped',
        'btn_factory_now' => 'Factory Reset now',
        'fr_step1' => 'Step 1/4: verifying credentials...',
        'fr_step2' => 'Step 2/4: expiring all session tokens...',
        'fr_step3' => 'Step 3/4: setting new administrator...',
        'fr_step4' => 'Step 4/4: rebuilding database...',
        'fr_complete' => 'Factory reset complete',
        'fr_complete_check' => 'Factory reset complete ✓',
        'fr_verify_failed' => 'Verify failed',
        'fr_step2_failed' => 'Step 2 failed',
        'fr_step3_failed' => 'Step 3 failed',
        'fr_rebuild_failed' => 'Rebuild failed',
        'fr_bad_user' => 'New admin username 3-20 letters/numbers/underscore',
        'fr_bad_pass' => 'New admin password min 8',
        'fr_confirm' => 'Please confirm before factory reset',
        /* 卸载 */
        'un_card' => 'Uninstall ChatApp',
        'un_note' => 'Permanently removes ChatApp from this server: deployed files, database (unless unchecked), and the WebSocket service. This cannot be undone.',
        'chk_un_db' => 'Delete database chatapp (uncheck to keep data)',
        'chk_un_risk' => 'I understand: everything will be deleted',
        'btn_uninstall' => 'Uninstall ChatApp',
        'un_confirm' => 'Please confirm before uninstalling',
        'un_confirm2' => 'Are you absolutely sure? This permanently deletes ChatApp and (by default) its database. This cannot be undone.',
        'un_done_title' => 'ChatApp has been uninstalled.',
        'un_done_sub' => 'Remaining files are being removed in the background. You can close this page now.',
        'un_done_flash' => 'ChatApp has been uninstalled',
        'un_failed' => 'Uninstall failed',
        /* 服务端错误（JSON error 字段） */
        'err_status_write' => 'Could not write status config (data/ not writable?).',
        'err_cur_pwd_required' => 'Current admin password is required.',
        'err_cur_pwd_wrong' => 'Current admin password incorrect.',
        'err_bad_m_user' => 'Invalid maintenance username.',
        'err_bad_m_pass' => 'Maintenance password min 8.',
        'err_creds_write' => 'Could not write maintenance config.',
        'err_db_down' => 'Database unreachable',
        'err_user_not_found' => 'User not found',
        'err_root_lock' => 'Cannot lock the root account',
        'err_unknown_action' => 'unknown action',
        /* 登录页 */
        'login_title' => 'Maintenance Portal Login',
        'login_h1' => 'Maintenance Portal',
        'login_sub' => 'Admin Login for Maintenance Mode',
        'login_user' => 'Maintenance Username',
        'login_pass' => 'Maintenance Password',
        'login_btn' => 'Log In',
        'login_doing' => 'Logging in...',
        'login_pow_fail' => 'Challenge failed. Please reload the page.',
        'login_failed' => 'Login failed.',
        'login_net' => 'Network error. Please try again.',
        'login_bad' => 'Invalid maintenance username or password.',
        'back_chat' => '← Back to ChatApp',
        'login_foot' => 'This login is used when the site is in maintenance mode.<br>Once logged in, you can control maintenance from the portal.',
    ],
    'zh' => [
        /* 通用 */
        'portal_name' => '维护门户',
        'lang_label' => '语言',
        'badge_maint' => '维护中',
        'badge_online' => '运行中',
        'yes' => '是',
        'no' => '否',
        'logout' => '退出登录',
        'logout_home' => '退出并返回到 ChatApp',
        'failed' => '失败',
        'net_err' => '网络错误 / 无响应',
        'all_fields_required' => '所有字段都要填',
        'git_hash_mismatch' => '两次 git 哈希不一致',
        /* 侧栏 */
        'nav_dash' => '仪表盘',
        'nav_settings' => '设置',
        'nav_creds' => '门户凭据',
        'nav_accounts' => '账号管理',
        'nav_upgrade' => '升级',
        'nav_downgrade' => '降级',
        'nav_factory' => '重置出厂',
        'nav_uninstall' => '卸载',
        'nav_links' => '快捷链接',
        /* 仪表盘 */
        'card_maint_mode' => '维护模式',
        'btn_enable_maint' => '开启维护模式',
        'btn_disable_maint' => '关闭维护模式',
        'note_visitors' => '所有访客都会看到维护页；门户与管理员凭据仍可登录。',
        'maint_on' => '已开启维护模式',
        'maint_off' => '已关闭维护模式',
        'card_current_settings' => '当前配置',
        'k_return_code' => '返回码',
        'k_maint_page' => '维护页面',
        'k_allow_login' => '允许维护登录',
        'k_use_mysql' => '使用 MySQL 凭据',
        'card_server_info' => '服务器信息',
        'k_git' => 'Git HEAD',
        'k_disk' => '剩余磁盘',
        'k_time' => '服务器时间',
        'reachable' => '可达',
        'down' => '不可达',
        'card_quick_actions' => '快捷操作',
        'link_maint_login' => '维护登录入口',
        /* 设置面板 */
        'set_card' => '维护模式设置',
        'lbl_maint_mode' => '维护模式',
        'opt_running' => '运行中（关闭维护）',
        'opt_maintenance' => '维护中（开启维护）',
        'chk_allow_login' => '允许维护登录（在维护页显示管理员登录入口）',
        'chk_mysql_creds' => '维护登录使用 MySQL 凭据（在数据库中校验账号）',
        'btn_save' => '保存',
        'btn_preview' => '预览页面',
        'note_changes' => '保存立即生效；预览会在新标签页打开所选维护页。',
        'settings_saved' => '设置已保存',
        'save_failed' => '保存失败',
        /* 门户凭据 */
        'creds_card' => '修改维护门户用户名 / 密码',
        'creds_note' => '需要验证当前管理员密码（UID 10000）。保存后旧维护令牌全部失效，需要重新登录。',
        'lbl_cur_pwd' => '当前管理员密码（必填）',
        'lbl_m_user' => '维护用户名（3-20 位）',
        'lbl_m_pass' => '维护密码（至少 8 位）',
        'btn_save_relogin' => '保存并重新登录',
        'need_cur_pwd' => '请先填写当前管理员密码',
        'bad_m_user' => '维护用户名必须是 3-20 位字母/数字/下划线',
        'bad_m_pass' => '维护密码至少 8 个字符',
        'creds_updated' => '凭据已更新，正在重新登录…',
        /* 账号锁定 */
        'acc_card' => '账号锁定管理',
        'acc_note' => '按用户名或 UID 查询账号，查看锁定状态（失败次数 / 解锁时间），可手动锁定或解锁。',
        'lbl_query' => '用户名或 UID',
        'ph_query' => '例如 admin 或 10001',
        'btn_lookup' => '查询',
        'need_query' => '请输入用户名或 UID',
        'not_found' => '未找到',
        'role_owner' => '站主',
        'role_admin' => '管理员',
        'role_user' => '用户',
        'ac_account' => '账号',
        'ac_display' => '显示名',
        'ac_role' => '角色',
        'ac_enabled' => '启用 / 占位号',
        'ac_restricted' => '受限',
        'ac_failed' => '失败次数',
        'ac_lock_status' => '锁定状态',
        'ac_last_login' => '最后登录',
        'ac_locked' => '已锁定',
        'ac_until' => '— 解锁时间',
        'ac_min_left' => '分钟后解锁',
        'ac_not_locked' => '未锁定',
        'ac_lock_for' => '锁定时长',
        'ac_min15' => '15 分钟',
        'ac_min30' => '30 分钟',
        'ac_hour1' => '1 小时',
        'ac_hour3' => '3 小时',
        'ac_hour24' => '24 小时',
        'ac_day7' => '7 天',
        'ac_lock_btn' => '锁定账号',
        'ac_unlock_btn' => '解锁账号',
        'ac_confirm_unlock' => '解锁该账号并清零失败次数？',
        'ac_locked_until' => '已锁定至 ',
        'ac_lock_failed' => '锁定失败',
        'ac_unlocked' => '账号已解锁',
        'ac_unlock_failed' => '解锁失败',
        /* 快捷链接 */
        'links_card' => '快捷入口',
        'link_relogin' => '维护登录（重新登录）',
        'links_note' => '危险操作（升级 / 降级 / 重置出厂 / 卸载）直接在左侧边栏对应面板里执行。',
        /* 升级 */
        'up_card' => '升级 ChatApp',
        'up_note' => '从 github.com/lqx211/ChatApp 拉取并覆盖代码；config/、data/ 会保留，维护凭据不会丢（maintenance/ 下的代码会正常更新）。未提交的改动会被覆盖。',
        'k_branch' => '分支',
        'k_current' => '当前',
        'k_remote' => '远程',
        'k_uncommitted' => '未提交',
        'btn_check_updates' => '检查更新',
        'btn_checking' => '检查中…',
        'lbl_admin_pwd' => '管理员密码（UID 10000）',
        'lbl_m_secret' => '维护口令',
        'lbl_git1' => '当前 git 哈希',
        'lbl_git2' => '再次输入 git 哈希',
        'chk_risk' => '我已了解并接受风险',
        'btn_upgrade_now' => '立即升级',
        'up_starting' => '开始…',
        'up_step_done' => '升级完成',
        'up_step_failed' => '升级失败',
        'up_check_failed' => '检查失败',
        'up_available' => '发现新版本 → ',
        'up_to_date' => '已是最新版本',
        'up_accept_risk' => '请先勾选「接受风险」',
        'up_started' => '升级已开始 —— 维护模式已就位',
        'up_released' => '升级失败 —— 已解除维护模式',
        'up_complete' => '升级完成 —— 服务已恢复',
        /* 降级 */
        'dg_card' => '系统降级',
        'dg_note' => '极度危险：把整个代码库回退到旧版本。数据库结构与代码可能不兼容，基本不可逆。',
        'lbl_current_ver' => '当前版本',
        'lbl_target_ver' => '选择目标版本',
        'chk_dg_risk' => '我明白这极度危险',
        'btn_downgrade_now' => '立即降级',
        'dg_loading' => '正在加载版本…',
        'dg_load_failed' => '版本列表加载失败',
        'dg_confirm' => '降级前请先确认',
        'dg_done' => '降级完成：',
        'dg_complete' => '降级完成',
        'dg_failed' => '降级失败',
        /* 重置出厂 */
        'fr_card' => '重置 ChatApp',
        'fr_note' => '删除并重建数据库、创建新管理员、清空所有用户与数据。默认会自动做一次 mysqldump 备份（除非勾选跳过）。',
        'lbl_new_admin' => '新管理员用户名（3-20 位）',
        'lbl_new_admin_pw' => '新管理员密码（至少 8 位）',
        'lbl_new_m_user' => '新维护用户名（可选）',
        'lbl_new_m_pass' => '新维护密码（可选）',
        'chk_skip_dump' => '跳过自动数据库备份',
        'chk_fr_risk' => '我明白所有数据将被清空',
        'btn_factory_now' => '立即重置',
        'fr_step1' => '第 1/4 步：验证凭据…',
        'fr_step2' => '第 2/4 步：使所有会话令牌失效…',
        'fr_step3' => '第 3/4 步：设置新管理员…',
        'fr_step4' => '第 4/4 步：重建数据库…',
        'fr_complete' => '重置完成',
        'fr_complete_check' => '重置完成 ✓',
        'fr_verify_failed' => '验证失败',
        'fr_step2_failed' => '第 2 步失败',
        'fr_step3_failed' => '第 3 步失败',
        'fr_rebuild_failed' => '重建失败',
        'fr_bad_user' => '新管理员用户名需 3-20 位字母/数字/下划线',
        'fr_bad_pass' => '新管理员密码至少 8 位',
        'fr_confirm' => '重置前请先确认',
        /* 卸载 */
        'un_card' => '卸载 ChatApp',
        'un_note' => '从服务器上永久移除 ChatApp：部署文件、数据库（取消勾选则保留）和 WebSocket 服务。不可撤销。',
        'chk_un_db' => '删除数据库 chatapp（取消勾选则保留数据）',
        'chk_un_risk' => '我明白：所有内容都会被删除',
        'btn_uninstall' => '卸载 ChatApp',
        'un_confirm' => '卸载前请先确认',
        'un_confirm2' => '真的要卸载吗？这会永久删除 ChatApp 及其数据库（默认），不可恢复。',
        'un_done_title' => 'ChatApp 已卸载。',
        'un_done_sub' => '剩余文件正在后台清理，现在可以关闭此页面了。',
        'un_done_flash' => 'ChatApp 已卸载',
        'un_failed' => '卸载失败',
        /* 服务端错误（JSON error 字段） */
        'err_status_write' => '状态配置写入失败（data/ 目录不可写？）',
        'err_cur_pwd_required' => '必须填写当前管理员密码。',
        'err_cur_pwd_wrong' => '当前管理员密码不正确。',
        'err_bad_m_user' => '维护用户名不合法（3-20 位字母/数字/下划线）。',
        'err_bad_m_pass' => '维护密码至少 8 位。',
        'err_creds_write' => '维护凭据写入失败。',
        'err_db_down' => '数据库不可达',
        'err_user_not_found' => '用户不存在',
        'err_root_lock' => '不能锁定站主账号',
        'err_unknown_action' => '未知操作',
        /* 登录页 */
        'login_title' => '维护门户登录',
        'login_h1' => '维护门户',
        'login_sub' => '维护模式管理员登录',
        'login_user' => '维护用户名',
        'login_pass' => '维护密码',
        'login_btn' => '登录',
        'login_doing' => '登录中…',
        'login_pow_fail' => '验证失败，请刷新页面重试。',
        'login_failed' => '登录失败。',
        'login_net' => '网络错误，请重试。',
        'login_bad' => '维护用户名或密码错误。',
        'back_chat' => '← 返回 ChatApp',
        'login_foot' => '此入口用于站点处于维护模式时登录。<br>登录后可在门户里控制维护状态。',
    ],
];
